version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambdatrip"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=\"anthropic.claude-3-haiku-20240307-v1:0\""
image_repositories = []
resolve_s3 = true
s3_prefix = "lambdatrip"
disable_rollback = true

[default.build]
[default.build.parameters]
use_container = false
cached = true
parallel = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER" 